contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/nyxb/contribute
    about: Please read through before making contributions.
  - name: ğŸ’¬ Nyxb's Discord Server
    url: https://chat.nyxb.yxz/
    about: Want to discuss / chat with the community? Here you go!
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://dev.to/nyxb/reproductions-3o7o
    about: Reproduction is very important for maintainer to help on your issues!
